name: lemmatizer
description: Lemmatizer for text in English. Inspired by Python's nltk.corpus.reader.wordnet.morphy
version: 2.0.0
#author: emrahdemirci <csemrahdemirci@gmail.com>
homepage: https://github.com/emrahdemirci/lemmatizer

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:


dev_dependencies:
  test:

